name: Samsung firmware extractor.

on:
  workflow_dispatch:
    inputs:
      model:
        description: 'Firmware model'
        required: true
        default: 'SM-A225F'
      csc:
        description: 'Firmware CSC code'
        required: true
        default: 'BKD'
      imei:
        description: 'Device IMEI'
        required: false
        default: ''
      upload_to_telegram:
        description: 'Upload to Telegram'
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository.
      uses: actions/checkout@v2

    - name: Installing packages.
      run: |
        sudo bash ./scripts/install_requirements.sh

    - name: Downloading firmware.
      run: |
        sudo bash ./scripts/download_firmware.sh ${{ github.event.inputs.model }} ${{ github.event.inputs.csc }}

    - name: Extracting firmware.
      run: |
        sudo bash ./scripts/extract_firmware.sh
