name: samfirm for download Samsung Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      model:
        description: 'Firmware model'
        required: true
        default: 'SM-A225F'
      imei:
        description: 'Device IMEI'
        required: true
        default: '356032730508566'
      region:
        description: 'Firmware CSC code'
        required: true
        default: 'BKD'
      upload_to_telegram:
        description: 'Upload to Telegram'
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Installing packages.
      run: |
        ./scripts/install_requirements.sh
